/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package payroll;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mharv
 */
public class table extends javax.swing.JFrame {

    /** Creates new form table */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void showTable(){
        try{
            String srch = "SELECT * FROM tblemployee";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = (PreparedStatement) con.prepareStatement(srch);
            rs = pst.executeQuery();
            tbl1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public table() {
        initComponents();
        showTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        btnsrch = new javax.swing.JButton();
        btnins = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        txtsrch = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        btnload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btndel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Name", "Pay/Hour", "Total Hours Worked", "Ovetime/Hour", "Total Overtime Hours", "Gross Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl1.getTableHeader().setReorderingAllowed(false);
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);
        if (tbl1.getColumnModel().getColumnCount() > 0) {
            tbl1.getColumnModel().getColumn(0).setResizable(false);
            tbl1.getColumnModel().getColumn(0).setPreferredWidth(11);
            tbl1.getColumnModel().getColumn(1).setResizable(false);
            tbl1.getColumnModel().getColumn(2).setResizable(false);
            tbl1.getColumnModel().getColumn(3).setResizable(false);
            tbl1.getColumnModel().getColumn(4).setResizable(false);
            tbl1.getColumnModel().getColumn(5).setResizable(false);
            tbl1.getColumnModel().getColumn(6).setResizable(false);
        }

        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });

        btnins.setText("Insert");
        btnins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsActionPerformed(evt);
            }
        });

        btndel.setText("delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnup.setText("Edit");
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        txtsrch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt6.setEditable(false);

        btnload.setText("Reload Database");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee Name:");

        jLabel2.setText("Pay per hour:");

        jLabel3.setText("Total hours worked:");

        jLabel4.setText("Overtime per hour");

        jLabel5.setText("Total overtime hours:");

        jLabel6.setText("Gross Pay:");

        jButton6.setText("Recently Deleted");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("View Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btndel1.setText("clear");
        btndel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt1)
                            .addComponent(txt2)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(txtsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsrch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsrch)
                    .addComponent(btnload)
                    .addComponent(jButton8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnins)
                            .addComponent(btnup)
                            .addComponent(btndel)
                            .addComponent(btndel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btninsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(txt2.getText()) ,
                n2 = Integer.parseInt(txt3.getText()) ,
                n3 = Integer.parseInt(txt4.getText()),
                n4 = Integer.parseInt(txt5.getText()),
                gp;
        
        gp = (n1*n2)+(n3*n4);
        txt6.setText(Integer.toString(gp));
                try{
                    String insrt = "INSERT INTO tblemployee "
                            + "(empName , payPerHr, totHrsWork, otPerHr , totalOt, grossPay)"
                            + "VALUES(?,?,?,?,?,?)";
                    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root", "");
                    pst = (PreparedStatement) con.prepareStatement(insrt);
                    pst.setString(1, txt1.getText());
                    pst.setInt(2, n1);
                    pst.setInt(3, n2);
                    pst.setInt(4, n3);
                    pst.setInt(5, n4);
                    pst.setInt(6, gp);
                    

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Inserted Successfully!");
                    showTable();
                    
               
                } catch (SQLException |HeadlessException ex) {
                    JOptionPane.showMessageDialog(null, ex);

                }
            
    }//GEN-LAST:event_btninsActionPerformed

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        // TODO add your handling code here:
        
        try{
            String srch = "SELECT * FROM tblemployee WHERE id = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = (PreparedStatement) con.prepareStatement(srch);
            pst.setInt(1, Integer.parseInt(txtsrch.getText()));
            rs = pst.executeQuery();
            tbl1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_btnloadActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(txt2.getText()) ,
                n2 = Integer.parseInt(txt3.getText()) ,
                n3 = Integer.parseInt(txt4.getText()),
                n4 = Integer.parseInt(txt5.getText()),
                gp;
        
        gp = (n1*n2)+(n3*n4);
        txt6.setText(Integer.toString(gp));
        try{
                String updt = "UPDATE tblemployee SET empName=? , payPerHr=?, totHrsWork=?, otPerHr =?, totalOt=?, grossPay=? WHERE id =? ";
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
                pst = (PreparedStatement) con.prepareStatement(updt);
                pst.setInt(7 , Integer.parseInt(txtsrch.getText()));
                pst.setString(1 , txt1.getText());
                pst.setInt(2, n1);
                pst.setInt(3, n2);
                pst.setInt(4, n3);
                pst.setInt(5, n4);
                pst.setInt(6, gp);
                
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null , "Updated successfully!");
                showTable();
                
            }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_btnupActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        int i = tbl1.getSelectedRow();
        TableModel model = tbl1.getModel();
        txtsrch.setText(model.getValueAt(i, 0).toString());
        txt1.setText(model.getValueAt(i, 1).toString());
        txt2.setText(model.getValueAt(i, 2).toString());
        txt3.setText(model.getValueAt(i, 3).toString());
        txt4.setText(model.getValueAt(i, 4).toString());
        txt5.setText(model.getValueAt(i, 5).toString());
        txt6.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tbl1MouseClicked

    private void btndel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndel1ActionPerformed
        // TODO add your handling code here:
        txtsrch.setText("");
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        
    }//GEN-LAST:event_btndel1ActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        int id , pph , thw , oph , tO , gp;
        String name;
        
        try{    
            String srch = "SELECT * FROM tblemployee WHERE id = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = (PreparedStatement) con.prepareStatement(srch);
            pst.setInt(1, Integer.parseInt(txtsrch.getText()));
            rs = pst.executeQuery();
            while(rs.next()){
                id = rs.getInt(1);
                name = rs.getString(2);
                pph = rs.getInt(3);
                thw = rs.getInt(4);
                oph = rs.getInt(5);
                tO = rs.getInt(6);
                gp = rs.getInt(7);
                
                try{
                String insrt = "INSERT INTO deldata(id , empName , payPerHour, totHrsWork, otPerHr , totalOt, grossPay) "
                    + "VALUES (?,?,?,?,?,?,?)";
                    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root", "");
                    pst = (PreparedStatement) con.prepareStatement(insrt);
                    pst.setInt(1 , id);
                    pst.setString(2, name);
                    pst.setInt(3, pph);
                    pst.setInt(4, thw);
                    pst.setInt(5, oph);
                    pst.setInt(6, tO);
                    pst.setInt(7, gp);
                    
                    pst.executeUpdate();
                }catch(SQLException |HeadlessException ex) {
                    JOptionPane.showMessageDialog(null, ex);

                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
        try{    
            String del = "DELETE FROM tblemployee WHERE id = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = (PreparedStatement) con.prepareStatement(del);
            pst.setInt(1, Integer.parseInt(txtsrch.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully." , "Delete" , JOptionPane.INFORMATION_MESSAGE);
            showTable();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        entry ent = new entry();
        this.dispose();
        ent.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Confirm" , JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(i == JOptionPane.YES_OPTION){
            login log = new login();
            this.dispose();
            log.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int id , pph , thw , oph , tO , gp;
        String name;
        
        try{    
            String srch = "SELECT * FROM tblemployee WHERE id = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = (PreparedStatement) con.prepareStatement(srch);
            pst.setInt(1, Integer.parseInt(txtsrch.getText()));
            rs = pst.executeQuery();
            while(rs.next()){
                id = rs.getInt(1);
                name = rs.getString(2);
                pph = rs.getInt(3);
                thw = rs.getInt(4);
                oph = rs.getInt(5);
                tO = rs.getInt(6);
                gp = rs.getInt(7);
                JOptionPane.showMessageDialog(null, "ID no.:     "+id+"\n\nEmployee name:     "+name
                +"\n\nPay per hour:     "+pph+"\n\nTotal hours worked:     "+thw
                +"\n\nOvertime per hour:     "+oph+"\n\nTotal overtime hours:     "+tO+"\n\nGross pay:     "+gp , "Information" , JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndel1;
    private javax.swing.JButton btnins;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton btnup;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txtsrch;
    // End of variables declaration//GEN-END:variables

}
